SELECT
	SUM(
		RO.ROOM_PRICE_GROSS + (
			(RT.ADULT_PRICE_GROSS * R.NUM_OF_ADULTS) + (RT.CHILD_PRICE_GROSS * R.NUM_OF_CHILDREN)
		)
	) AS "total"
FROM
	RESERVATION R
	LEFT JOIN RESERVATION_ROOM RR ON RR.RESERVATION_ID = R.ID
	LEFT JOIN ROOM RO ON RO.ID = RR.ROOM_ID
	LEFT JOIN ROOM_TYPE RT ON RT.ID = RO.ROOM_TYPE_ID
WHERE
	R.ID = 2;

SELECT
	SUM(
		ROOM_GROSS_PRICE + (
			(
				ROOM_GROSS_PRICE_ADULT * RESERVATION_NUMBER_OF_ADULTS
			) + (
				ROOM_GROSS_PRICE_CHILD * RESERVATION_NUMBER_OF_CHILDREN
			)
		)
	) INTO PRICE_GROSS
FROM
	RESERVATION_VIEW RV
	LEFT JOIN INVOICE_VIEW IV ON IV.INVOICE_RESERVATION_ID = RV.RESERVATION_ID
	LEFT JOIN ROOM_VIEW ROV ON ROV.ROOM_ID = RV.RESERVATION_ROOM_ID
WHERE
	RV.RESERVATION_ID = 2;

SELECT
	RESERVATION_ID,
	RESERVATION_ROOM_ID,
	RESERVATION_NUMBER_OF_ADULTS,
	RESERVATION_NUMBER_OF_CHILDREN,
	RESERVATION_END_DATE - RESERVATION_START_DATE AS "days",
	INVOICE_PRICE_GROSS AS "total",
	(
		ROOM_GROSS_PRICE + (
			(
				ROOM_GROSS_PRICE_ADULT * RESERVATION_NUMBER_OF_ADULTS
			) + (
				ROOM_GROSS_PRICE_CHILD * RESERVATION_NUMBER_OF_CHILDREN
			)
		)
	) AS "unit price"
FROM
	RESERVATION_VIEW RV
	LEFT JOIN INVOICE_VIEW IV ON IV.INVOICE_RESERVATION_ID = RV.RESERVATION_ID
	LEFT JOIN ROOM_VIEW ROV ON ROV.ROOM_ID = RV.RESERVATION_ROOM_ID
ORDER BY
	RESERVATION_ID;