CREATE SEQUENCE IF NOT EXISTS invoice_id_seq
    START WITH 50
    INCREMENT BY 1
    NO MAXVALUE
    NO CYCLE;

CREATE SEQUENCE IF NOT EXISTS reservation_id_seq
    START WITH 50
    INCREMENT BY 1
    NO MAXVALUE
    NO CYCLE;

CREATE SEQUENCE IF NOT EXISTS room_type_id_seq
    START WITH 50
    INCREMENT BY 1
    NO MAXVALUE
    NO CYCLE;

CREATE SEQUENCE IF NOT EXISTS service_id_seq
    START WITH 50
    INCREMENT BY 1
    NO MAXVALUE
    NO CYCLE;

CREATE SEQUENCE IF NOT EXISTS user_account_id_seq
    START WITH 50
    INCREMENT BY 1
    NO MAXVALUE
    NO CYCLE;

CREATE SEQUENCE IF NOT EXISTS room_id_seq
    START WITH 50
    INCREMENT BY 1
    NO MAXVALUE
    NO CYCLE;